author: deathline75
database: true
description: >
            MCWorld Manager by deathline75
main: me.deathline75.main.MCWorld
name: MCWorld
startup: postworld
version: '1.2'
commands:
       mcw:
         description: Head command for MCWorld
         usage: <command> <variable>